# Site settings
title:          yobs0814 기억저장소
description:    ""
baseurl:        ""
url:            https://yobs0814.github.io

# Author
author:
  name:         Yoseph Noh
  url:
  email:        yobs0814@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
